-- DENGO POS – Migration v4: Messaging module
-- Run in SSMS against DENGO_POS before running: npx prisma generate
-- Stop backend first, then restart after generate.

-- ── Portal messages (teacher ↔ admin, linked to an order) ─────────────────────
CREATE TABLE PORTAL_MESSAGES (
  ID            NVARCHAR(36)   NOT NULL,
  PORTAL_ORDER_ID NVARCHAR(36) NULL,
  TEACHER_ID    NVARCHAR(36)   NOT NULL,
  SENDER_ROLE   NVARCHAR(10)   NOT NULL,  -- 'TEACHER' | 'ADMIN'
  BODY          NVARCHAR(MAX)  NOT NULL,
  IS_READ       BIT            NOT NULL CONSTRAINT DF_PMSG_IS_READ DEFAULT 0,
  CREATED_AT    DATETIME2      NOT NULL CONSTRAINT DF_PMSG_CREATED_AT DEFAULT GETDATE(),
  CONSTRAINT PK_PORTAL_MESSAGES PRIMARY KEY (ID),
  CONSTRAINT FK_PMSG_ORDER   FOREIGN KEY (PORTAL_ORDER_ID) REFERENCES PORTAL_ORDERS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PMSG_TEACHER FOREIGN KEY (TEACHER_ID)      REFERENCES TEACHERS(ID)      ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- ── Internal messages (staff ↔ staff) ─────────────────────────────────────────
CREATE TABLE INTERNAL_MESSAGES (
  ID           NVARCHAR(36)  NOT NULL,
  FROM_USER_ID NVARCHAR(36)  NOT NULL,
  TO_USER_ID   NVARCHAR(36)  NOT NULL,
  BODY         NVARCHAR(MAX) NOT NULL,
  IS_READ      BIT           NOT NULL CONSTRAINT DF_IMSG_IS_READ DEFAULT 0,
  READ_AT      DATETIME2     NULL,
  CREATED_AT   DATETIME2     NOT NULL CONSTRAINT DF_IMSG_CREATED_AT DEFAULT GETDATE(),
  CONSTRAINT PK_INTERNAL_MESSAGES PRIMARY KEY (ID),
  CONSTRAINT FK_IMSG_FROM FOREIGN KEY (FROM_USER_ID) REFERENCES USERS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_IMSG_TO   FOREIGN KEY (TO_USER_ID)   REFERENCES USERS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
