-- ── portal_migration_v3.sql ────────────────────────────────────────────────
-- Run ONCE against DENGO_POS after portal_migration_v2.sql
-- Adds: educational levels, grade breakdown, limitPerStudent, purchase tracking

-- ── 1. TEACHER_SCHOOLS: educational level column ────────────────────────────
ALTER TABLE TEACHER_SCHOOLS ADD EDUCATIONAL_LEVEL NVARCHAR(20) NULL;
GO

-- ── 2. PORTAL_ORDERS: level, student count, grade summary ───────────────────
ALTER TABLE PORTAL_ORDERS ADD EDUCATIONAL_LEVEL  NVARCHAR(20)  NULL;
ALTER TABLE PORTAL_ORDERS ADD STUDENT_COUNT      INT           NULL;
ALTER TABLE PORTAL_ORDERS ADD ORDER_GRADE_SUMMARY NVARCHAR(300) NULL;
GO

-- ── 3. PROGRAM_CONFIGS: limit per student ───────────────────────────────────
ALTER TABLE PROGRAM_CONFIGS ADD LIMIT_PER_STUDENT DECIMAL(18,2) NULL;
GO

-- ── 4. PORTAL_ORDER_GRADES ──────────────────────────────────────────────────
CREATE TABLE PORTAL_ORDER_GRADES (
  ID              NVARCHAR(36)  NOT NULL,
  PORTAL_ORDER_ID NVARCHAR(36)  NOT NULL,
  GRADE_NAME      NVARCHAR(100) NOT NULL,
  STUDENT_COUNT   INT           NOT NULL,
  CONSTRAINT PK_PORTAL_ORDER_GRADES  PRIMARY KEY (ID),
  CONSTRAINT FK_POG_PORTAL_ORDER
    FOREIGN KEY (PORTAL_ORDER_ID) REFERENCES PORTAL_ORDERS(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

-- ── 5. PROGRAM_OPTION_LEVELS ────────────────────────────────────────────────
CREATE TABLE PROGRAM_OPTION_LEVELS (
  PROGRAM_OPTION_ID NVARCHAR(36) NOT NULL,
  LEVEL             NVARCHAR(20) NOT NULL,
  CONSTRAINT PK_PROGRAM_OPTION_LEVELS PRIMARY KEY (PROGRAM_OPTION_ID, LEVEL),
  CONSTRAINT FK_POL_PROGRAM_OPTION
    FOREIGN KEY (PROGRAM_OPTION_ID) REFERENCES PROGRAM_OPTIONS(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

-- ── 6. PORTAL_PURCHASE_TRACKING ─────────────────────────────────────────────
CREATE TABLE PORTAL_PURCHASE_TRACKING (
  ID            NVARCHAR(36)  NOT NULL,
  PRODUCT_ID    NVARCHAR(36)  NOT NULL,
  PROGRAM_TYPE  NVARCHAR(30)  NOT NULL,
  FISCAL_YEAR   INT           NOT NULL,
  PURCHASED_QTY DECIMAL(18,4) NOT NULL
    CONSTRAINT DF_PPT_PURCHASED_QTY DEFAULT 0,
  NOTES         NVARCHAR(500) NULL,
  UPDATED_AT    DATETIME2     NOT NULL
    CONSTRAINT DF_PPT_UPDATED_AT DEFAULT GETDATE(),
  UPDATED_BY_ID NVARCHAR(36)  NULL,
  CONSTRAINT PK_PORTAL_PURCHASE_TRACKING  PRIMARY KEY (ID),
  CONSTRAINT UQ_PPT_PRODUCT_PROGRAM_YEAR  UNIQUE (PRODUCT_ID, PROGRAM_TYPE, FISCAL_YEAR),
  CONSTRAINT FK_PPT_PRODUCT
    FOREIGN KEY (PRODUCT_ID)    REFERENCES PRODUCTS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PPT_USER
    FOREIGN KEY (UPDATED_BY_ID) REFERENCES USERS(ID)    ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO
