-- ============================================================
--  DENGO POS  ·  SQL Server Database Schema
--  Compatible: SQL Server 2019+ / Azure SQL
--  Charset: UTF-16 (NVARCHAR throughout)
-- ============================================================

USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'DENGO_POS')
  CREATE DATABASE DENGO_POS COLLATE Latin1_General_CI_AI;
GO

USE DENGO_POS;
GO

-- ============================================================
--  SECTION 1 – CORE TABLES
-- ============================================================

-- ── Branches / Stores ────────────────────────────────────────
CREATE TABLE BRANCHES (
  ID               NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  NAME             NVARCHAR(150) NOT NULL,
  CODE             NVARCHAR(20)  NOT NULL  UNIQUE,
  TYPE             NVARCHAR(20)  NOT NULL  DEFAULT 'branch'  CHECK (TYPE IN ('main','branch')),
  ADDRESS          NVARCHAR(255) NOT NULL  DEFAULT '',
  CITY             NVARCHAR(100) NOT NULL  DEFAULT '',
  PHONE            NVARCHAR(30)  NOT NULL  DEFAULT '',
  EMAIL            NVARCHAR(150) NOT NULL  DEFAULT '',
  MANAGER          NVARCHAR(150) NOT NULL  DEFAULT '',
  STATUS           NVARCHAR(20)  NOT NULL  DEFAULT 'active'  CHECK (STATUS IN ('active','inactive','maintenance')),
  OPEN_TIME        NVARCHAR(5)   NOT NULL  DEFAULT '08:00',
  CLOSE_TIME       NVARCHAR(5)   NOT NULL  DEFAULT '20:00',
  -- Config (stored flat, avoid JSON for SQL Server compat)
  CURRENCY         NVARCHAR(10)  NOT NULL  DEFAULT 'GTQ',
  TIMEZONE         NVARCHAR(60)  NOT NULL  DEFAULT 'America/Guatemala',
  TAX_RATE         DECIMAL(5,4)  NOT NULL  DEFAULT 0.12,
  PRINTER_ENABLED  BIT           NOT NULL  DEFAULT 1,
  CREATED_AT       DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT       DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
GO

-- ── Users ─────────────────────────────────────────────────────
CREATE TABLE USERS (
  ID            NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  EMAIL         NVARCHAR(150) NOT NULL  UNIQUE,
  NAME          NVARCHAR(150) NOT NULL,
  PASSWORD_HASH NVARCHAR(255) NOT NULL,
  ROLE          NVARCHAR(30)  NOT NULL  CHECK (ROLE IN ('ADMIN','AUDITOR','INVENTORY_CONTROL','OPERATOR')),
  BRANCH_ID     NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  IS_ACTIVE     BIT           NOT NULL  DEFAULT 1,
  CREATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_USERS_BRANCH_ID ON USERS(BRANCH_ID);
CREATE INDEX IX_USERS_EMAIL     ON USERS(EMAIL);
GO

-- ── Categories ────────────────────────────────────────────────
CREATE TABLE CATEGORIES (
  ID          NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  NAME        NVARCHAR(100) NOT NULL,
  DESCRIPTION NVARCHAR(500)     NULL,
  COLOR       NVARCHAR(30)      NULL,
  IS_ACTIVE   BIT           NOT NULL  DEFAULT 1,
  CREATED_AT  DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT  DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
GO

-- ── Product Units ─────────────────────────────────────────────
CREATE TABLE PRODUCT_UNITS (
  ID           NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  NAME         NVARCHAR(60)  NOT NULL,
  ABBREVIATION NVARCHAR(10)  NOT NULL,
  TYPE         NVARCHAR(20)  NOT NULL  CHECK (TYPE IN ('DISCRETE','CONTINUOUS')),
  CREATED_AT   DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
GO

-- ── Products ──────────────────────────────────────────────────
CREATE TABLE PRODUCTS (
  ID          NVARCHAR(36)   NOT NULL  PRIMARY KEY,
  BARCODE     NVARCHAR(50)       NULL  UNIQUE,
  SKU         NVARCHAR(50)       NULL,
  NAME        NVARCHAR(200)  NOT NULL,
  BRAND       NVARCHAR(100)      NULL,
  DESCRIPTION NVARCHAR(MAX)      NULL,
  BASE_PRICE  DECIMAL(18,2)  NOT NULL  DEFAULT 0,
  COST        DECIMAL(18,2)  NOT NULL  DEFAULT 0,
  IMAGE_URL   NVARCHAR(500)      NULL,
  CATEGORY_ID NVARCHAR(36)   NOT NULL  REFERENCES CATEGORIES(ID),
  BASE_UNIT_ID NVARCHAR(36)  NOT NULL  REFERENCES PRODUCT_UNITS(ID),
  MIN_STOCK   INT            NOT NULL  DEFAULT 0,
  SALES_COUNT INT            NOT NULL  DEFAULT 0,
  IS_ACTIVE   BIT            NOT NULL  DEFAULT 1,
  CREATED_AT  DATETIME2(7)   NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT  DATETIME2(7)   NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_PRODUCTS_CATEGORY_ID ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IX_PRODUCTS_BARCODE     ON PRODUCTS(BARCODE) WHERE BARCODE IS NOT NULL;
CREATE INDEX IX_PRODUCTS_NAME        ON PRODUCTS(NAME);
GO

-- ── Product Variations ────────────────────────────────────────
CREATE TABLE PRODUCT_VARIATIONS (
  ID                NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  PRODUCT_ID        NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
  NAME              NVARCHAR(100) NOT NULL,
  BARCODE           NVARCHAR(50)      NULL,
  CONVERSION_FACTOR DECIMAL(18,4) NOT NULL  DEFAULT 1,
  PRICE             DECIMAL(18,2) NOT NULL,
  IS_DEFAULT        BIT           NOT NULL  DEFAULT 0,
  CREATED_AT        DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_PRODUCT_VARIATIONS_PRODUCT_ID ON PRODUCT_VARIATIONS(PRODUCT_ID);
CREATE INDEX IX_PRODUCT_VARIATIONS_BARCODE    ON PRODUCT_VARIATIONS(BARCODE) WHERE BARCODE IS NOT NULL;
GO

-- ── Product Attributes ────────────────────────────────────────
CREATE TABLE PRODUCT_ATTRIBUTES (
  ID         NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  PRODUCT_ID NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
  ATTR_NAME  NVARCHAR(100) NOT NULL,
  ATTR_VALUE NVARCHAR(255) NOT NULL
);
CREATE INDEX IX_PRODUCT_ATTRIBUTES_PRODUCT_ID ON PRODUCT_ATTRIBUTES(PRODUCT_ID);
GO

-- ── Inventory ─────────────────────────────────────────────────
CREATE TABLE INVENTORY (
  ID              NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  PRODUCT_ID      NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  BRANCH_ID       NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  QUANTITY        DECIMAL(18,4) NOT NULL  DEFAULT 0,
  LAST_RESTOCK_AT DATETIME2(7)      NULL,
  LAST_SALE_AT    DATETIME2(7)      NULL,
  UPDATED_AT      DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  CONSTRAINT UQ_INVENTORY_PRODUCT_BRANCH UNIQUE (PRODUCT_ID, BRANCH_ID)
);
CREATE INDEX IX_INVENTORY_PRODUCT_ID ON INVENTORY(PRODUCT_ID);
CREATE INDEX IX_INVENTORY_BRANCH_ID  ON INVENTORY(BRANCH_ID);
GO

-- ── Stock Movements (complete audit trail) ────────────────────
CREATE TABLE STOCK_MOVEMENTS (
  ID              NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  PRODUCT_ID      NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  BRANCH_ID       NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  TYPE            NVARCHAR(20)  NOT NULL  CHECK (TYPE IN ('IN','OUT','ADJUSTMENT','TRANSFER','SALE','RETURN')),
  QUANTITY        DECIMAL(18,4) NOT NULL,
  QUANTITY_BEFORE DECIMAL(18,4)     NULL,
  QUANTITY_AFTER  DECIMAL(18,4)     NULL,
  REASON          NVARCHAR(500)     NULL,
  REFERENCE_ID    NVARCHAR(36)      NULL,  -- SALE_ID / PURCHASE_ORDER_ID / TRANSFER_ID
  PERFORMED_BY_ID NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  CREATED_AT      DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_STOCK_MOVEMENTS_PRODUCT_ID ON STOCK_MOVEMENTS(PRODUCT_ID);
CREATE INDEX IX_STOCK_MOVEMENTS_BRANCH_ID  ON STOCK_MOVEMENTS(BRANCH_ID);
CREATE INDEX IX_STOCK_MOVEMENTS_TYPE       ON STOCK_MOVEMENTS(TYPE);
CREATE INDEX IX_STOCK_MOVEMENTS_CREATED_AT ON STOCK_MOVEMENTS(CREATED_AT DESC);
GO

-- ── Customers ─────────────────────────────────────────────────
CREATE TABLE CUSTOMERS (
  ID           NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  NIT          NVARCHAR(30)  NOT NULL  UNIQUE,
  NAME         NVARCHAR(150) NOT NULL,
  EMAIL        NVARCHAR(150)     NULL,
  PHONE        NVARCHAR(30)      NULL,
  ADDRESS      NVARCHAR(300)     NULL,
  CREDIT_LIMIT DECIMAL(18,2) NOT NULL  DEFAULT 0,
  CREDIT_USED  DECIMAL(18,2) NOT NULL  DEFAULT 0,
  IS_ACTIVE    BIT           NOT NULL  DEFAULT 1,
  CREATED_AT   DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT   DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_CUSTOMERS_NIT  ON CUSTOMERS(NIT);
CREATE INDEX IX_CUSTOMERS_NAME ON CUSTOMERS(NAME);
GO

-- ── Suppliers ─────────────────────────────────────────────────
CREATE TABLE SUPPLIERS (
  ID            NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  CODE          NVARCHAR(30)  NOT NULL  UNIQUE,
  NAME          NVARCHAR(150) NOT NULL,
  CONTACT_NAME  NVARCHAR(150) NOT NULL  DEFAULT '',
  EMAIL         NVARCHAR(150)     NULL,
  PHONE         NVARCHAR(30)      NULL,
  ADDRESS       NVARCHAR(300)     NULL,
  CITY          NVARCHAR(100)     NULL,
  TAX_ID        NVARCHAR(30)      NULL,  -- NIT/RFC
  PAYMENT_TERMS NVARCHAR(50)  NOT NULL  DEFAULT 'Contado',
  CREDIT_LIMIT  DECIMAL(18,2)     NULL,
  NOTES         NVARCHAR(MAX)     NULL,
  IS_ACTIVE     BIT           NOT NULL  DEFAULT 1,
  RATING        TINYINT           NULL  CHECK (RATING BETWEEN 1 AND 5),
  CREATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_SUPPLIERS_NAME ON SUPPLIERS(NAME);
GO

-- ============================================================
--  SECTION 2 – CASH REGISTER
-- ============================================================

CREATE TABLE CASH_REGISTERS (
  ID              NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  BRANCH_ID       NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  OPENED_BY_ID    NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  CLOSED_BY_ID    NVARCHAR(36)      NULL  REFERENCES USERS(ID),
  OPENED_AT       DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  CLOSED_AT       DATETIME2(7)      NULL,
  INITIAL_AMOUNT  DECIMAL(18,2) NOT NULL,
  FINAL_AMOUNT    DECIMAL(18,2)     NULL,
  EXPECTED_AMOUNT DECIMAL(18,2)     NULL,
  DIFFERENCE      DECIMAL(18,2)     NULL,
  STATUS          NVARCHAR(10)  NOT NULL  DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN','CLOSED')),
  -- Sales summary (updated via trigger/service)
  TOTAL_SALES     DECIMAL(18,2) NOT NULL  DEFAULT 0,
  SALES_COUNT     INT           NOT NULL  DEFAULT 0,
  CASH_SALES      DECIMAL(18,2) NOT NULL  DEFAULT 0,
  CARD_SALES      DECIMAL(18,2) NOT NULL  DEFAULT 0,
  TRANSFER_SALES  DECIMAL(18,2) NOT NULL  DEFAULT 0,
  CREATED_AT      DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT      DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_CASH_REGISTERS_BRANCH_ID ON CASH_REGISTERS(BRANCH_ID);
CREATE INDEX IX_CASH_REGISTERS_STATUS    ON CASH_REGISTERS(STATUS);
GO

CREATE TABLE CASH_MOVEMENTS (
  ID               NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  CASH_REGISTER_ID NVARCHAR(36)  NOT NULL  REFERENCES CASH_REGISTERS(ID),
  TYPE             NVARCHAR(10)  NOT NULL  CHECK (TYPE IN ('INCOME','EXPENSE')),
  AMOUNT           DECIMAL(18,2) NOT NULL,
  DESCRIPTION      NVARCHAR(500) NOT NULL,
  PERFORMED_BY_ID  NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  CREATED_AT       DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_CASH_MOVEMENTS_CASH_REGISTER_ID ON CASH_MOVEMENTS(CASH_REGISTER_ID);
GO

-- ============================================================
--  SECTION 3 – SALES
-- ============================================================

CREATE TABLE SALES (
  ID               NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  INVOICE_NUMBER   NVARCHAR(50)  NOT NULL  UNIQUE,
  BRANCH_ID        NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  CASHIER_ID       NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  CUSTOMER_ID      NVARCHAR(36)      NULL  REFERENCES CUSTOMERS(ID),
  CASH_REGISTER_ID NVARCHAR(36)      NULL  REFERENCES CASH_REGISTERS(ID),
  SUBTOTAL         DECIMAL(18,2) NOT NULL,
  TAX              DECIMAL(18,2) NOT NULL  DEFAULT 0,
  DISCOUNT         DECIMAL(18,2) NOT NULL  DEFAULT 0,
  TOTAL            DECIMAL(18,2) NOT NULL,
  PAYMENT_METHOD   NVARCHAR(20)  NOT NULL  CHECK (PAYMENT_METHOD IN ('CASH','CARD','TRANSFER','MIXED','CREDIT')),
  SALE_TYPE        NVARCHAR(10)  NOT NULL  CHECK (SALE_TYPE IN ('CASH','CREDIT')),
  DUE_DATE         DATETIME2(7)      NULL,
  IS_PAID          BIT           NOT NULL  DEFAULT 1,
  PAID_AMOUNT      DECIMAL(18,2)     NULL,
  IS_VOIDED        BIT           NOT NULL  DEFAULT 0,
  VOIDED_BY_ID     NVARCHAR(36)      NULL  REFERENCES USERS(ID),
  VOIDED_AT        DATETIME2(7)      NULL,
  NOTES            NVARCHAR(MAX)     NULL,
  CREATED_AT       DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_SALES_BRANCH_ID        ON SALES(BRANCH_ID);
CREATE INDEX IX_SALES_CASHIER_ID       ON SALES(CASHIER_ID);
CREATE INDEX IX_SALES_CUSTOMER_ID      ON SALES(CUSTOMER_ID);
CREATE INDEX IX_SALES_CREATED_AT       ON SALES(CREATED_AT DESC);
CREATE INDEX IX_SALES_SALE_TYPE        ON SALES(SALE_TYPE);
CREATE INDEX IX_SALES_PAYMENT_METHOD   ON SALES(PAYMENT_METHOD);
CREATE INDEX IX_SALES_CASH_REGISTER_ID ON SALES(CASH_REGISTER_ID);
GO

CREATE TABLE SALE_ITEMS (
  ID           NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  SALE_ID      NVARCHAR(36)  NOT NULL  REFERENCES SALES(ID) ON DELETE CASCADE,
  PRODUCT_ID   NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  VARIATION_ID NVARCHAR(36)      NULL  REFERENCES PRODUCT_VARIATIONS(ID),
  QUANTITY     DECIMAL(18,4) NOT NULL,
  UNIT_PRICE   DECIMAL(18,2) NOT NULL,
  DISCOUNT     DECIMAL(5,4)  NOT NULL  DEFAULT 0,   -- 0.00-1.00
  TOTAL        DECIMAL(18,2) NOT NULL
);
CREATE INDEX IX_SALE_ITEMS_SALE_ID    ON SALE_ITEMS(SALE_ID);
CREATE INDEX IX_SALE_ITEMS_PRODUCT_ID ON SALE_ITEMS(PRODUCT_ID);
GO

-- ============================================================
--  SECTION 4 – PURCHASE ORDERS
-- ============================================================

CREATE TABLE PURCHASE_ORDERS (
  ID            NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  ORDER_NUMBER  NVARCHAR(30)  NOT NULL  UNIQUE,
  SUPPLIER_ID   NVARCHAR(36)  NOT NULL  REFERENCES SUPPLIERS(ID),
  BRANCH_ID     NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  SUBTOTAL      DECIMAL(18,2) NOT NULL,
  TAX           DECIMAL(18,2) NOT NULL  DEFAULT 0,
  TOTAL         DECIMAL(18,2) NOT NULL,
  STATUS        NVARCHAR(20)  NOT NULL  DEFAULT 'DRAFT'
                CHECK (STATUS IN ('DRAFT','PENDING','PARTIAL','RECEIVED','CANCELLED')),
  EXPECTED_DATE DATETIME2(7)      NULL,
  RECEIVED_DATE DATETIME2(7)      NULL,
  NOTES         NVARCHAR(MAX)     NULL,
  CREATED_BY_ID NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  RECEIVED_BY_ID NVARCHAR(36)     NULL  REFERENCES USERS(ID),
  CREATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_PURCHASE_ORDERS_SUPPLIER_ID ON PURCHASE_ORDERS(SUPPLIER_ID);
CREATE INDEX IX_PURCHASE_ORDERS_BRANCH_ID   ON PURCHASE_ORDERS(BRANCH_ID);
CREATE INDEX IX_PURCHASE_ORDERS_STATUS      ON PURCHASE_ORDERS(STATUS);
CREATE INDEX IX_PURCHASE_ORDERS_CREATED_AT  ON PURCHASE_ORDERS(CREATED_AT DESC);
GO

CREATE TABLE PURCHASE_ORDER_ITEMS (
  ID                NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  PURCHASE_ORDER_ID NVARCHAR(36)  NOT NULL  REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
  PRODUCT_ID        NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  PRODUCT_NAME      NVARCHAR(200) NOT NULL,   -- snapshot at time of order
  QUANTITY          DECIMAL(18,4) NOT NULL,
  RECEIVED_QUANTITY DECIMAL(18,4) NOT NULL  DEFAULT 0,
  UNIT_COST         DECIMAL(18,2) NOT NULL,
  TOTAL             DECIMAL(18,2) NOT NULL
);
CREATE INDEX IX_PURCHASE_ORDER_ITEMS_PURCHASE_ORDER_ID ON PURCHASE_ORDER_ITEMS(PURCHASE_ORDER_ID);
GO

-- ============================================================
--  SECTION 5 – TRANSFERS
-- ============================================================

CREATE TABLE TRANSFERS (
  ID              NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  FROM_BRANCH_ID  NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  TO_BRANCH_ID    NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  STATUS          NVARCHAR(20)  NOT NULL  DEFAULT 'PENDING'
                  CHECK (STATUS IN ('PENDING','APPROVED','IN_TRANSIT','RECEIVED','REJECTED')),
  NOTES           NVARCHAR(MAX)     NULL,
  REQUESTED_BY_ID NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  APPROVED_BY_ID  NVARCHAR(36)      NULL  REFERENCES USERS(ID),
  RECEIVED_BY_ID  NVARCHAR(36)      NULL  REFERENCES USERS(ID),
  CREATED_AT      DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  APPROVED_AT     DATETIME2(7)      NULL,
  RECEIVED_AT     DATETIME2(7)      NULL
);
CREATE INDEX IX_TRANSFERS_FROM_BRANCH_ID ON TRANSFERS(FROM_BRANCH_ID);
CREATE INDEX IX_TRANSFERS_TO_BRANCH_ID   ON TRANSFERS(TO_BRANCH_ID);
CREATE INDEX IX_TRANSFERS_STATUS         ON TRANSFERS(STATUS);
GO

CREATE TABLE TRANSFER_ITEMS (
  ID          NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  TRANSFER_ID NVARCHAR(36)  NOT NULL  REFERENCES TRANSFERS(ID) ON DELETE CASCADE,
  PRODUCT_ID  NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  QUANTITY    DECIMAL(18,4) NOT NULL
);
CREATE INDEX IX_TRANSFER_ITEMS_TRANSFER_ID ON TRANSFER_ITEMS(TRANSFER_ID);
GO

-- ============================================================
--  SECTION 6 – QUOTATIONS
-- ============================================================

CREATE TABLE QUOTATIONS (
  ID                   NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  QUOTATION_NUMBER     NVARCHAR(30)  NOT NULL  UNIQUE,
  BRANCH_ID            NVARCHAR(36)  NOT NULL  REFERENCES BRANCHES(ID),
  CUSTOMER_ID          NVARCHAR(36)  NOT NULL  REFERENCES CUSTOMERS(ID),
  SUBTOTAL             DECIMAL(18,2) NOT NULL,
  TAX                  DECIMAL(18,2) NOT NULL  DEFAULT 0,
  DISCOUNT             DECIMAL(18,2) NOT NULL  DEFAULT 0,
  TOTAL                DECIMAL(18,2) NOT NULL,
  STATUS               NVARCHAR(20)  NOT NULL  DEFAULT 'DRAFT'
                       CHECK (STATUS IN ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','CONVERTED')),
  VALID_UNTIL          DATETIME2(7)  NOT NULL,
  NOTES                NVARCHAR(MAX)     NULL,
  CREATED_BY_ID        NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  CONVERTED_TO_SALE_ID NVARCHAR(36)      NULL  REFERENCES SALES(ID),
  CREATED_AT           DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE(),
  UPDATED_AT           DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_QUOTATIONS_BRANCH_ID   ON QUOTATIONS(BRANCH_ID);
CREATE INDEX IX_QUOTATIONS_CUSTOMER_ID ON QUOTATIONS(CUSTOMER_ID);
CREATE INDEX IX_QUOTATIONS_STATUS      ON QUOTATIONS(STATUS);
GO

CREATE TABLE QUOTATION_ITEMS (
  ID           NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  QUOTATION_ID NVARCHAR(36)  NOT NULL  REFERENCES QUOTATIONS(ID) ON DELETE CASCADE,
  PRODUCT_ID   NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  VARIATION_ID NVARCHAR(36)      NULL  REFERENCES PRODUCT_VARIATIONS(ID),
  QUANTITY     DECIMAL(18,4) NOT NULL,
  UNIT_PRICE   DECIMAL(18,2) NOT NULL,
  DISCOUNT     DECIMAL(5,4)  NOT NULL  DEFAULT 0,
  TOTAL        DECIMAL(18,2) NOT NULL
);
CREATE INDEX IX_QUOTATION_ITEMS_QUOTATION_ID ON QUOTATION_ITEMS(QUOTATION_ID);
GO

-- ============================================================
--  SECTION 7 – AUDIT & LOGS
-- ============================================================

-- General activity audit log
CREATE TABLE AUDIT_LOGS (
  ID         NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  USER_ID    NVARCHAR(36)      NULL  REFERENCES USERS(ID),
  ACTION     NVARCHAR(50)  NOT NULL,  -- CREATE, UPDATE, DELETE, LOGIN, LOGOUT, VOID, APPROVE, etc.
  ENTITY     NVARCHAR(60)  NOT NULL,  -- Sale, Product, PurchaseOrder, etc.
  ENTITY_ID  NVARCHAR(36)      NULL,
  OLD_VALUES NVARCHAR(MAX)     NULL,  -- JSON snapshot before change
  NEW_VALUES NVARCHAR(MAX)     NULL,  -- JSON snapshot after change
  IP_ADDRESS NVARCHAR(45)      NULL,
  USER_AGENT NVARCHAR(500)     NULL,
  CREATED_AT DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_AUDIT_LOGS_USER_ID    ON AUDIT_LOGS(USER_ID);
CREATE INDEX IX_AUDIT_LOGS_ACTION     ON AUDIT_LOGS(ACTION);
CREATE INDEX IX_AUDIT_LOGS_ENTITY     ON AUDIT_LOGS(ENTITY);
CREATE INDEX IX_AUDIT_LOGS_ENTITY_ID  ON AUDIT_LOGS(ENTITY_ID);
CREATE INDEX IX_AUDIT_LOGS_CREATED_AT ON AUDIT_LOGS(CREATED_AT DESC);
GO

-- Login history (auth security)
CREATE TABLE LOGIN_HISTORY (
  ID          NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  USER_ID     NVARCHAR(36)      NULL  REFERENCES USERS(ID),
  EMAIL       NVARCHAR(150) NOT NULL,
  SUCCESS     BIT           NOT NULL,
  IP_ADDRESS  NVARCHAR(45)      NULL,
  USER_AGENT  NVARCHAR(500)     NULL,
  FAIL_REASON NVARCHAR(200)     NULL,
  CREATED_AT  DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_LOGIN_HISTORY_USER_ID    ON LOGIN_HISTORY(USER_ID);
CREATE INDEX IX_LOGIN_HISTORY_EMAIL      ON LOGIN_HISTORY(EMAIL);
CREATE INDEX IX_LOGIN_HISTORY_CREATED_AT ON LOGIN_HISTORY(CREATED_AT DESC);
GO

-- Price change history
CREATE TABLE PRICE_HISTORY (
  ID            NVARCHAR(36)  NOT NULL  PRIMARY KEY,
  PRODUCT_ID    NVARCHAR(36)  NOT NULL  REFERENCES PRODUCTS(ID),
  FIELD         NVARCHAR(30)  NOT NULL,  -- 'BASE_PRICE', 'COST', variation price
  OLD_VALUE     DECIMAL(18,2) NOT NULL,
  NEW_VALUE     DECIMAL(18,2) NOT NULL,
  CHANGED_BY_ID NVARCHAR(36)  NOT NULL  REFERENCES USERS(ID),
  CREATED_AT    DATETIME2(7)  NOT NULL  DEFAULT GETUTCDATE()
);
CREATE INDEX IX_PRICE_HISTORY_PRODUCT_ID ON PRICE_HISTORY(PRODUCT_ID);
CREATE INDEX IX_PRICE_HISTORY_CREATED_AT ON PRICE_HISTORY(CREATED_AT DESC);
GO

-- ============================================================
--  SECTION 8 – TRIGGERS
-- ============================================================

-- Trigger: log product price changes
CREATE OR ALTER TRIGGER TRG_PRODUCTS_PRICE_AUDIT
ON PRODUCTS
AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  -- Log BASE_PRICE change
  INSERT INTO PRICE_HISTORY (ID, PRODUCT_ID, FIELD, OLD_VALUE, NEW_VALUE, CHANGED_BY_ID, CREATED_AT)
  SELECT
    LOWER(NEWID()),
    i.ID,
    'BASE_PRICE',
    d.BASE_PRICE,
    i.BASE_PRICE,
    i.ID, -- CHANGED_BY_ID placeholder; service layer should log with real userId
    GETUTCDATE()
  FROM inserted i
  INNER JOIN deleted d ON i.ID = d.ID
  WHERE i.BASE_PRICE <> d.BASE_PRICE;

  -- Log COST change
  INSERT INTO PRICE_HISTORY (ID, PRODUCT_ID, FIELD, OLD_VALUE, NEW_VALUE, CHANGED_BY_ID, CREATED_AT)
  SELECT
    LOWER(NEWID()),
    i.ID,
    'COST',
    d.COST,
    i.COST,
    i.ID,
    GETUTCDATE()
  FROM inserted i
  INNER JOIN deleted d ON i.ID = d.ID
  WHERE i.COST <> d.COST;

  -- Update UPDATED_AT
  UPDATE PRODUCTS SET UPDATED_AT = GETUTCDATE()
  FROM PRODUCTS p INNER JOIN inserted i ON p.ID = i.ID;
END;
GO

-- Trigger: keep CASH_REGISTERS.UPDATED_AT fresh
CREATE OR ALTER TRIGGER TRG_CASH_REGISTERS_UPDATED_AT
ON CASH_REGISTERS
AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE CASH_REGISTERS SET UPDATED_AT = GETUTCDATE()
  FROM CASH_REGISTERS cr INNER JOIN inserted i ON cr.ID = i.ID;
END;
GO

-- Trigger: keep USERS.UPDATED_AT fresh
CREATE OR ALTER TRIGGER TRG_USERS_UPDATED_AT
ON USERS
AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE USERS SET UPDATED_AT = GETUTCDATE()
  FROM USERS u INNER JOIN inserted i ON u.ID = i.ID;
END;
GO

-- Trigger: keep CUSTOMERS CREDIT_AVAILABLE consistent
-- CREDIT_AVAILABLE is computed: CREDIT_LIMIT - CREDIT_USED (not stored, computed in query)
-- Trigger validates CREDIT_USED never exceeds CREDIT_LIMIT
CREATE OR ALTER TRIGGER TRG_CUSTOMERS_CREDIT_GUARD
ON CUSTOMERS
AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  IF EXISTS (SELECT 1 FROM inserted WHERE CREDIT_USED > CREDIT_LIMIT)
  BEGIN
    RAISERROR('CREDIT_USED cannot exceed CREDIT_LIMIT', 16, 1);
    ROLLBACK;
  END;
  UPDATE CUSTOMERS SET UPDATED_AT = GETUTCDATE()
  FROM CUSTOMERS c INNER JOIN inserted i ON c.ID = i.ID;
END;
GO

-- Trigger: auto-update SALES aggregate on CASH_REGISTER when sale inserted
-- NOTE: The service layer handles this. Trigger is a safety net.
CREATE OR ALTER TRIGGER TRG_SALES_UPDATE_REGISTER_TOTALS
ON SALES
AFTER INSERT
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE CASH_REGISTERS
  SET
    TOTAL_SALES    = TOTAL_SALES    + i.TOTAL,
    SALES_COUNT    = SALES_COUNT    + 1,
    CASH_SALES     = CASH_SALES     + CASE WHEN i.PAYMENT_METHOD = 'CASH'     THEN i.TOTAL ELSE 0 END,
    CARD_SALES     = CARD_SALES     + CASE WHEN i.PAYMENT_METHOD = 'CARD'     THEN i.TOTAL ELSE 0 END,
    TRANSFER_SALES = TRANSFER_SALES + CASE WHEN i.PAYMENT_METHOD = 'TRANSFER' THEN i.TOTAL ELSE 0 END,
    UPDATED_AT     = GETUTCDATE()
  FROM CASH_REGISTERS cr
  INNER JOIN inserted i ON cr.ID = i.CASH_REGISTER_ID
  WHERE i.CASH_REGISTER_ID IS NOT NULL
    AND i.IS_VOIDED = 0;
END;
GO

-- ============================================================
--  SECTION 9 – USEFUL VIEWS
-- ============================================================

-- Current stock with product info
CREATE OR ALTER VIEW VW_CURRENT_STOCK AS
SELECT
  inv.ID          AS INVENTORY_ID,
  p.ID            AS PRODUCT_ID,
  p.NAME          AS PRODUCT_NAME,
  p.BARCODE,
  p.MIN_STOCK,
  cat.NAME        AS CATEGORY_NAME,
  b.ID            AS BRANCH_ID,
  b.NAME          AS BRANCH_NAME,
  inv.QUANTITY    AS CURRENT_STOCK,
  CASE
    WHEN inv.QUANTITY <= 0           THEN 'OUT_OF_STOCK'
    WHEN inv.QUANTITY <= p.MIN_STOCK THEN 'LOW_STOCK'
    ELSE                                  'OK'
  END             AS STOCK_STATUS,
  inv.UPDATED_AT  AS LAST_UPDATED
FROM INVENTORY inv
INNER JOIN PRODUCTS p      ON p.ID = inv.PRODUCT_ID  AND p.IS_ACTIVE = 1
INNER JOIN CATEGORIES cat  ON cat.ID = p.CATEGORY_ID
INNER JOIN BRANCHES b      ON b.ID = inv.BRANCH_ID;
GO

-- Daily sales summary
CREATE OR ALTER VIEW VW_DAILY_SALES_SUMMARY AS
SELECT
  CAST(s.CREATED_AT AS DATE)  AS SALE_DATE,
  s.BRANCH_ID,
  b.NAME                      AS BRANCH_NAME,
  COUNT(s.ID)                 AS SALES_COUNT,
  SUM(s.TOTAL)                AS TOTAL_REVENUE,
  SUM(s.DISCOUNT)             AS TOTAL_DISCOUNTS,
  SUM(CASE WHEN s.PAYMENT_METHOD = 'CASH'     THEN s.TOTAL ELSE 0 END) AS CASH_REVENUE,
  SUM(CASE WHEN s.PAYMENT_METHOD = 'CARD'     THEN s.TOTAL ELSE 0 END) AS CARD_REVENUE,
  SUM(CASE WHEN s.PAYMENT_METHOD = 'TRANSFER' THEN s.TOTAL ELSE 0 END) AS TRANSFER_REVENUE
FROM SALES s
INNER JOIN BRANCHES b ON b.ID = s.BRANCH_ID
WHERE s.IS_VOIDED = 0
GROUP BY CAST(s.CREATED_AT AS DATE), s.BRANCH_ID, b.NAME;
GO

-- Top products by sales count
CREATE OR ALTER VIEW VW_TOP_PRODUCTS AS
SELECT
  p.ID              AS PRODUCT_ID,
  p.NAME            AS PRODUCT_NAME,
  cat.NAME          AS CATEGORY_NAME,
  p.BASE_PRICE,
  p.COST,
  p.SALES_COUNT,
  p.BASE_PRICE - p.COST AS MARGIN
FROM PRODUCTS p
INNER JOIN CATEGORIES cat ON cat.ID = p.CATEGORY_ID
WHERE p.IS_ACTIVE = 1;
GO

-- ============================================================
--  SECTION 10 – STORED PROCEDURES (helpers)
-- ============================================================

-- Close a cash register safely
CREATE OR ALTER PROCEDURE SP_CLOSE_CASH_REGISTER
  @REGISTER_ID   NVARCHAR(36),
  @CLOSED_BY_ID  NVARCHAR(36),
  @FINAL_AMOUNT  DECIMAL(18,2)
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRANSACTION;
  BEGIN TRY
    DECLARE @INITIAL_AMOUNT  DECIMAL(18,2);
    DECLARE @TOTAL_MOVEMENTS DECIMAL(18,2);
    DECLARE @TOTAL_SALES     DECIMAL(18,2);
    DECLARE @EXPECTED_AMOUNT DECIMAL(18,2);

    SELECT
      @INITIAL_AMOUNT = INITIAL_AMOUNT,
      @TOTAL_SALES    = TOTAL_SALES
    FROM CASH_REGISTERS WHERE ID = @REGISTER_ID AND STATUS = 'OPEN';

    IF @@ROWCOUNT = 0
    BEGIN
      RAISERROR('Cash register not found or already closed', 16, 1);
      ROLLBACK;
      RETURN;
    END

    SELECT @TOTAL_MOVEMENTS = COALESCE(
      SUM(CASE WHEN TYPE = 'INCOME' THEN AMOUNT ELSE -AMOUNT END), 0
    )
    FROM CASH_MOVEMENTS WHERE CASH_REGISTER_ID = @REGISTER_ID;

    SET @EXPECTED_AMOUNT = @INITIAL_AMOUNT + @TOTAL_SALES + @TOTAL_MOVEMENTS;

    UPDATE CASH_REGISTERS SET
      STATUS          = 'CLOSED',
      CLOSED_BY_ID    = @CLOSED_BY_ID,
      CLOSED_AT       = GETUTCDATE(),
      FINAL_AMOUNT    = @FINAL_AMOUNT,
      EXPECTED_AMOUNT = @EXPECTED_AMOUNT,
      DIFFERENCE      = @FINAL_AMOUNT - @EXPECTED_AMOUNT,
      UPDATED_AT      = GETUTCDATE()
    WHERE ID = @REGISTER_ID;

    INSERT INTO AUDIT_LOGS (ID, USER_ID, ACTION, ENTITY, ENTITY_ID, CREATED_AT)
    VALUES (LOWER(NEWID()), @CLOSED_BY_ID, 'CLOSE', 'CASH_REGISTER', @REGISTER_ID, GETUTCDATE());

    COMMIT;
  END TRY
  BEGIN CATCH
    ROLLBACK;
    THROW;
  END CATCH;
END;
GO

-- Update inventory stock with movement record
CREATE OR ALTER PROCEDURE SP_UPDATE_STOCK
  @PRODUCT_ID      NVARCHAR(36),
  @BRANCH_ID       NVARCHAR(36),
  @DELTA           DECIMAL(18,4),
  @MOVEMENT_TYPE   NVARCHAR(20),
  @REASON          NVARCHAR(500),
  @PERFORMED_BY_ID NVARCHAR(36),
  @REFERENCE_ID    NVARCHAR(36)
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRANSACTION;
  BEGIN TRY
    DECLARE @CURRENT_QTY DECIMAL(18,4) = 0;
    DECLARE @NEW_QTY     DECIMAL(18,4);
    DECLARE @INV_ID      NVARCHAR(36);

    SELECT @INV_ID = ID, @CURRENT_QTY = QUANTITY
    FROM INVENTORY
    WHERE PRODUCT_ID = @PRODUCT_ID AND BRANCH_ID = @BRANCH_ID;

    SET @NEW_QTY = CASE WHEN @CURRENT_QTY + @DELTA < 0 THEN 0 ELSE @CURRENT_QTY + @DELTA END;

    IF @INV_ID IS NULL
    BEGIN
      SET @INV_ID = LOWER(NEWID());
      INSERT INTO INVENTORY (ID, PRODUCT_ID, BRANCH_ID, QUANTITY, UPDATED_AT)
      VALUES (@INV_ID, @PRODUCT_ID, @BRANCH_ID, @NEW_QTY, GETUTCDATE());
    END
    ELSE
    BEGIN
      UPDATE INVENTORY
      SET QUANTITY        = @NEW_QTY,
          UPDATED_AT      = GETUTCDATE(),
          LAST_SALE_AT    = CASE WHEN @MOVEMENT_TYPE = 'SALE' THEN GETUTCDATE() ELSE LAST_SALE_AT    END,
          LAST_RESTOCK_AT = CASE WHEN @MOVEMENT_TYPE = 'IN'   THEN GETUTCDATE() ELSE LAST_RESTOCK_AT END
      WHERE ID = @INV_ID;
    END

    -- Update product sales counter for SALE type
    IF @MOVEMENT_TYPE = 'SALE'
      UPDATE PRODUCTS SET SALES_COUNT = SALES_COUNT + ABS(@DELTA), UPDATED_AT = GETUTCDATE()
      WHERE ID = @PRODUCT_ID;

    INSERT INTO STOCK_MOVEMENTS (
      ID, PRODUCT_ID, BRANCH_ID, TYPE, QUANTITY,
      QUANTITY_BEFORE, QUANTITY_AFTER, REASON, REFERENCE_ID, PERFORMED_BY_ID, CREATED_AT
    )
    VALUES (
      LOWER(NEWID()), @PRODUCT_ID, @BRANCH_ID, @MOVEMENT_TYPE, ABS(@DELTA),
      @CURRENT_QTY, @NEW_QTY, @REASON, @REFERENCE_ID, @PERFORMED_BY_ID, GETUTCDATE()
    );

    COMMIT;
  END TRY
  BEGIN CATCH
    ROLLBACK;
    THROW;
  END CATCH;
END;
GO
