// A real Guatemalan NIT is digits (optionally with a trailing check
// digit/letter after a dash). "CF"/"C/F" (Consumidor Final), placeholder
// values generated by the migration script (SIN-NIT-*), and anything else
// non-numeric (a surname, a program code) are not fiscal IDs — they're fine
// as Customer.nit for day-to-day sales, but not valid to bill a factura to.
export function looksLikeRealNit(raw: string | null | undefined): boolean {
  const v = (raw ?? '').trim().toUpperCase()
  if (!v || v === 'CF' || v === 'C/F' || v === 'C-F' || v.startsWith('SIN-NIT-')) return false
  return /^\d[\d-]{0,14}[\dA-Z]?$/.test(v) && /\d{4,}/.test(v)
}
